---
- name: Upgrade pip
  pip:
    name: pip
    state: latest
    executable: pip3

- name: Send requirements.txt
  copy:
    src: requirements.txt
    dest: "{{ requirement_path }}"
    owner: root
    group: root
    mode: '0755'

- name: Install pip dependencies for my Flask project
  pip:
    requirements: "{{ requirement_path }}"
    executable: pip3

- name: Ensure project path exist
  file:
    path: "{{ flask_project_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Clone Flask project
  git:
    repo: https://github.com/gabyfulchic/search-morty.git
    dest: "{{ flask_project_path }}"
    clone: true

- name: Launch the Flask Project in local
  environment:
    FLASK_APP: "{{ flask_project_path }}/app/routes.py"
  shell: |
    flask run -h 127.0.0.1 -p 80&
  when:
    - project == "local"

- name: Expose the Flask Project on Https
  environment:
    FLASK_APP: "{{ flask_project_path }}/app/routes.py"
  shell: |
    flask run -h 0.0.0.0 -p 443 --cert={{ cert_path }} --key={{ key_path }}&
  when:
    - project == "exposed"
