---
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: docker_centos7
    image: jrei/systemd-centos:7
    dockerfile: Dockerfile.j2
    privileged: true
provisioner:
  name: ansible
  playbooks:
    converge: ../../converge.yaml
  inventory:
    links:
      host_vars: ../../host_vars
  log: true
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../../tests
  lint:
    name: flake8
